vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        article:
            uri_prefix: /image/article
            upload_destination: '%kernel.project_dir%/public/image/article'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        user:
            uri_prefix: /image/user
            upload_destination: '%kernel.project_dir%/public/image/user'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        pub:
            uri_prefix: /image/pub
            upload_destination: '%kernel.project_dir%/public/image/pub'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        type:
            uri_prefix: /image/type
            upload_destination: '%kernel.project_dir%/public/image/type'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
